### ISSUE TITLE
ORM R&D

### ISSUE THREAD

**Issue by Mathieu414** [Atmos4/intranoseV2#23]
OBJECTIF:
- pouvoir avoir une base de donnée locale facile à mettre en place
- pouvoir facilement mettre à jour la base de donnée en production sans
avoir à aller taper des requêtes manuellement dans phpMyAdmin

**Comment by Mathieu414** [comment]
![Image](https://user-images.githubusercontent.com/46241768/221701061-f7d08e6a-d2c0-4695-8057-4357f9ab3d27.svg)

**Comment by Mathieu414** [comment]
![Image](https://user-images.githubusercontent.com/46241768/222096751-89b3a40d-e44d-4ca5-af09-7854a937acc5.svg)

**Comment by Atmos4** [comment]
Solved by #28
