### ISSUE TITLE
Migrate users to families

### ISSUE THREAD

**Issue by Atmos4** [Atmos4/intranoseV2#91]
Should be relatively easy to do because a similar feature exists in the old intranose

**Comment by Mathieu414** [comment]
An idea for updating the families : 
`$family_list = $database->query('SELECT DISTINCT parent FROM licencies WHERE valid=1 and invisible=0 and parent!=0')->fetchAll();
foreach ($family_list as $family) {
    // create new family
    $newFamily = new Family();
    // get the parent of the family from the old db
    $stmt = $database->prepare('SELECT nom, prenom FROM licencies WHERE id=:id');
    $stmt->bindParam(':id', $family['parent']);
    $stmt->execute();
    $result = $stmt->fetchAll();
    // match the parent with the new database corresponding user
    $parent = em()->getRepository(User::class)->findOneBy(['first_name' => $result[0]['prenom'], 'last_name' => $result[0]['nom']]);
    // set the parent as the family leader
    $parent->family = $newFamily;
    $parent->$family_leader = true;
    em()->persist($parent);
    // get the children of the family from the old db
    $stmt = $database->prepare('SELECT nom, prenom FROM licencies WHERE parent=:id');
    $stmt->bindParam(':id', $family['parent']);
    $stmt->execute();
    $result = $stmt->fetchAll();
    // match the children with the new database corresponding user
    foreach ($result as $child) {
        $child = em()->getRepository(User::class)->findOneBy(['first_name' => $child['prenom'], 'last_name' => $child['nom']]);
        $child->family = $newFamily;
        em()->persist($child);
    }
    em()->persist($newFamily);
}`

**Comment by Mathieu414** [comment]
Closing this issue as we don't need to migrate families
